Update
crrio/maple.fm pull request #21
Opened 2017-03-17 01:03 UTC by crr

2017-03-17 01:06 UTC, Inumedia requested changes
Pls fix 😘

2017-03-17 01:06 UTC, Inumedia commented on public/js/crrio.marketFunc.js
> +  //if (val.V) {
Commented out code should be removed

2017-03-17 01:06 UTC, Inumedia commented on public/js/jquery.rss.js
> +(function ($) {
Is there supposed to not be a header on this? Who created this lib?

2017-03-17 01:06 UTC, Inumedia commented on resources/views/market/search.blade.php
>      <style>
There shouldn't be <style> elements

2017-03-17 01:06 UTC, Inumedia commented on resources/views/statistics/home.blade.php
> +<div class="alert-dev red white-text center" style="font-size:20px;"><i class="fa fa-exclamation-circle"></i> <b>Heads up!</b> All the statistics on this page are randomly generated and will be repla
There shouldn't be style attributes

2017-03-17 01:06 UTC, Inumedia commented on resources/views/welcome.blade.php
> +<p class="white-text" id="news"></p>
Why is this empty

2017-03-17 01:06 UTC, Inumedia commented on resources/views/welcome.blade.php
> +<script>
There shouldn't be inline javascript calls

2017-03-17 01:09 UTC, corsair commented on public/js/crrio.marketFunc.js
> +  //if (val.V) {
This was commented out as a temporary motion, as the market data is currently not producing accurate nebulite information, resulting in the "if" for val.V continuing when it otherwise shouldn't. (nebulites appearing on chairs)

2017-03-17 01:12 UTC, Inumedia commented on public/js/crrio.marketFunc.js
>    itemDetails += '<small class="text-muted">' + val.P + '</small>';
Why are we still using single letter variable names, we should be migrating to the more friendly format

2017-03-17 01:16 UTC, crr commented on public/js/jquery.rss.js
> +(function ($) {
There is no header present in the original source:
https://github.com/sdepold/jquery-rss

2017-03-17 01:20 UTC, crr commented on resources/views/welcome.blade.php
> +<p class="white-text" id="news"></p>
It's filled with data from the jQuery.

2017-03-17 01:21 UTC, crr commented on public/js/crrio.marketFunc.js
>    itemDetails += '<small class="text-muted">' + val.P + '</small>';
We can revisit this in the future or create an issue, as functionality is not effected by the current variable names.

2017-03-17 01:24 UTC, crr commented on resources/views/market/search.blade.php
>      <style>
Fixed.

2017-03-17 01:24 UTC, crr commented on resources/views/statistics/home.blade.php
> +<div class="alert-dev red white-text center" style="font-size:20px;"><i class="fa fa-exclamation-circle"></i> <b>Heads up!</b> All the statistics on this page are randomly generated and will be repla
Fixed.

2017-03-19 01:58 UTC, crr commented on resources/views/welcome.blade.php
> +<script>
Fixed.

2017-03-19 02:44 UTC, merged

2017-03-21 00:33 UTC, Acen commented on resources/views/welcome.blade.php
>  @section('js')
Should look at changing this to a `@stack`.